#!/bin/bash -l
#SBATCH --job-name=BAM_Coverage_DS
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --mem=50G
#SBATCH --partition=batch
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=bistbs@miamioh.edu
#SBATCH --output=logs/CoverageDS_%A.out
#SBATCH --error=logs/CoverageDS_%A.err

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#         Load modules / dependencies       #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

module load samtools-1.22.1
module load RStudio-2025.05.1


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#         Paths and filenames               #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
BAM="/scratch/bistbs_new/4_aligning_with_BWA_Mem_Final_1/5_Sorted_BAMs/6_ReadGroups/8_MarkDuplicates/all_samples_merged_rmdup.bam"
COVERAGE_FILE="${BAM%.bam}_coverage.gz"
R_SCRIPT="scripts/bam_cov_DS.R"

# Create logs directory
mkdir -p logs

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#        Step 1: Compute coverage           #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
echo "🔹 Calculating coverage for $BAM ..."
samtools coverage "$BAM" | gzip > "$COVERAGE_FILE"
echo "✅ Coverage stats saved to $COVERAGE_FILE"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#       Step 2: Run R script for DS        #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
echo "🔹 Running R script for downsampling proportions ..."
Rscript "$R_SCRIPT"
echo "✅ R downsampling script finished"

